theme: jekyll-theme-midnight
title: Braeden McGrath
description: Driven computer engineer seeking an internship that fosters skill development and embraces a passion for technology. I am interested in hardware engineering as well as network engineering. I am looking for opportunities to learn and become a better computer engineer.
