theme: jekyll-theme-cayman
title: Braeden McGrath
description: I am a driven computer engineer seeking opportunities to apply and expand technical expertise through hands-on engineering challenges and continuous learning. I have experience in hardware testing, team collaboration, and problem solving. I am passionate about computer architecture and embedded systems.
