theme: jekyll-theme-minimal
title: Braeden McGrath
subtitle: About
description: I am a junior computer engineering student at the University of Tennessee at Chattanooga. I am seeking an internship that fosters skill development and embraces a passion for technology. I am interested in hardware engineering and network engineering. I am looking for opportunities to learn and become a better computer engineer.
