theme: jekyll-theme-cayman
title: Braeden McGrath
description: I am a senior computer engineering student at the University of Tennessee at Chattanooga. I am seeking an internship that fosters skill development and embraces a passion for technology. I am interested in hardware engineering and embedded engineering. I am looking for opportunities to learn new skills and grow as an engineer.
